const enchantmentTranslations = {
    "fire_aspect": "Fire Aspect",
    "multishot": "Multishot",
    "luck_of_the_sea": "Luck of the Sea",
    "binding_curse": "Curse of Binding",
    "knockback": "Knockback",
    "frost_walker": "Frost Walker",
    "unbreaking": "Unbreaking",
    "fortune": "Fortune",
    "channeling": "Channeling",
    "loyalty": "Loyalty",
    "protection": "Protection",
    "smite": "Smite",
    "vanishing_curse": "Curse of Vanishing",
    "punch": "Punch",
    "flame": "Flame",
    "piercing": "Piercing",
    "projectile_protection": "Projectile Protection",
    "looting": "Looting",
    "respiration": "Respiration",
    "riptide": "Riptide",
    "quick_charge": "Quick Charge",
    "lure": "Lure",
    "fire_protection": "Fire Protection",
    "thorns": "Thorns",
    "feather_falling": "Feather Falling",
    "power": "Power",
    "infinity": "Infinity",
    "sharpness": "Sharpness",
    "impaling": "Impaling",
    "efficiency": "Efficiency",
    "sweeping": "Sweeping Edge",
    "mending": "Mending",
    "depth_strider": "Depth Strider",
    "blast_protection": "Blast Protection",
    "silk_touch": "Silk Touch",
    "soul_speed": "Soul Speed",
    "aqua_affinity": "Aqua Affinity",
    "bane_of_arthropods": "Bane of Arthropods",
    "swift_sneak": "Swift Sneak",
    "wind_burst": "Wind Burst",
    "density": "Density",
    "breach": "Breach",
};

module.exports = enchantmentTranslations;